from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.cell(0, 10, 'Schemo Eligibility Report', new_x="LMARGIN", new_y="NEXT", align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Generated by Schemo  | Page {self.page_no()}', align='C')

def create_pdf(ai_results):
    
    pdf = PDF()
    pdf.add_page()
    
    
    # Recommendations Section
    pdf.set_font("Helvetica", 'B', 12)
    ai_results = ai_results.encode('latin-1', 'ignore').decode('latin-1')
    pdf.cell(0, 10, "  Recommended Schemes", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(2)
    
    pdf.set_font("Helvetica", '', 10)
    
    # Clean up Markdown
    clean_results = str(ai_results).replace("**", "").replace("₹", "Rs. ").replace("---", "\n" + "-"*60 + "\n")
    pdf.multi_cell(0, 8, clean_results)
    
    # 3. Disclaimer
    pdf.ln(10)
    pdf.set_font("Helvetica", 'I', 8)
    pdf.multi_cell(0, 5, "DISCLAIMER: This report is generated by AI. Please verify criteria on official portals.")
    

    return bytes(pdf.output())
